#!/usr/bin/env bash
# performs Redirection
sudo apt-get update && sudo apt-get install nginx -y
echo "Hello World!" > index.html
sudo cp index.html /var/www/html/index.nginx-debian.html
sudo sed -i 's/server_name\ \_/server_name\ \_/redirect;return 301 $https://www.youtube.com/watch?v=QH2-TGUlwu4;/g' /etc/nginx/sites-available/default
sudo service nginx restart
