#!/usr/bin/env bash
# performs Redirection
sudo apt-get update && sudo apt-get install nginx -y
echo "Hello World!" > index.html
sudo cp index.html /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server; location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx start
