#!/usr/bin/env bash
# contains a custom header
setheader="add\_header X\-Served\-By \"$HOSTNAME\"\;location"
sudo sed -i "s/location/$setheader/" /etc/nginx/sites-enabled/default
sudo service nginx restart
