#!/usr/bin/env bash
# install your load balancer
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\* -y
setproxy="
frontend http
	bind *:80
	mode http
	default_backend web-servers
backend web-servers
	balance roundrobin
	server 47094-web-01 34.207.155.28:80 check
	server 47094-web-02 35.174.204.156:80 check"
echo "$setproxy" | sudo tee -a etc/haproxy/haproxy.cfg
sudo service haproxy start
