#!/usr/bin/env bash
# install your load balancer
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\* -y
setproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers\nbackend web-servers\n\tbalance roundrobin\n\tserver 47094-web-01 100.26.17.30\n\tserver 47094-web-02 100.26.226.160"
echo "$setproxy" | sudo tee -a etc/haproxy/haproxy.cfg
sudo service haproxy start
