#!/usr/bin/env bash
# install your load balancer
setproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers\nbackend web-servers\n\tbalance roundrobin\n\tserver 47094-web-01 100.26.17.30\n\tserver 47094-web-02 100.26.226.160"
echo "$setproxy" >> /etc/haproxy/haproxy.cfg
