#!/usr/bin/env bash
# localhost  to 127.0.0.2
# change facebook.com  to 8.8.8.8
cp /etc/hosts ~/host.new
echo "127.0.0.2     localhost">~/host.new
echo "8.8.8.8       facebook.com">>~/host.new
cp ~/host.new /etc/hosts